### PR TITLE
Review of Kelly

### PR DESCRIPTION
**Pull request by mlharaujo**
Created new subsection in the Appendix, explaining the necessary results from Kelly's book.

Made some changes to the non-semisimple appendix subsection.

### CODE REVIEW

**Comment by jcguu95** [comment]
Do you want to try resolving the conflict? Usually, one accepts the PR when it is without conflict. If you don't want to, I can also close this PR, and manually copy and paste your content.

**Comment by mlharaujo** [comment]
> Do you want to try resolving the conflict? Usually, one accepts the PR when it is without conflict. If you don't want to, I can also close this PR, and manually copy and paste your content.

Ok, I will try!

**Comment by mlharaujo** [comment]
> > Do you want to try resolving the conflict? Usually, one accepts the PR when it is without conflict. If you don't want to, I can also close this PR, and manually copy and paste your content.
> 
> Ok, I will try!

I don't see how to do it. Can you just copy paste the three appendices "The non-semisimple case", "Review of necessary results from \cite{kelly/basic-concepts-enriched" and "Rigidity" into your branch? Then I can pull from you to get all the structural changes you made. Thanks!

**Comment by jcguu95** [comment]
Okay! I have done that in this [commit](https://github.com/jcguu95/skein-construction-of-balanced-tensor-product/commit/79069e97c7a0f74cb05ac8cbdf3a4108df79f7ef). 

Note that I have demoted two subsections to subsubsections. I also commented out the inclusion of the images, as I wish that we unify our image inclusion procedure. Todos are added, and we can fix those later.

(I haven't included your pictures though. Please keep them and add them later while you resolve those todos.)

**Pull request closed without merging**
